### ISSUE TITLE
unnecessary `unsafe`  block error with rustc 1.39.0-nightly 

### ISSUE THREAD

**Issue by 3for** [rust-lang/packed_simd#265]
git clone the source code, and run `cargo build`， an "unnecessary `unsafe`  block" error occurred.
My rust version is `rustc 1.39.0-nightly (9b91b9c10 2019-08-26)`.
![image](https://user-images.githubusercontent.com/30716372/63833900-a61a3400-c9a6-11e9-8053-66fc0e6d3ed8.png)

It will be solved by remove the `unsafe` block.
![image](https://user-images.githubusercontent.com/30716372/63834141-36587900-c9a7-11e9-8418-be518405cd97.png)

**Comment by gnzlbg** [comment]
The better fix here is to remove the `#[deny(warnings)]` from the `lib.rs` and instead pass it to cargo in CI via RUSTFLAGS.

**Comment by 3for** [comment]
Good idea. I've open the warnings instead of remove `unsafe` block.

**Comment by Lokathor** [comment]
@3for if i understand correctly, by changing the warning level you've resolved this particular problem? Should we close the issue?

**Comment by 3for** [comment]
@Lokathor Yes, we can close this issue.
