### ISSUE TITLE
no mathching package named `stdsimd-test` found

### ISSUE THREAD

**Issue by 3for** [rust-lang/packed_simd#266]
```
cd verify/verify
RUSTFLAGS="-C target-feature=+avx2" cargo test --release
```
Error occured:

![image](https://user-images.githubusercontent.com/30716372/63834546-21c8b080-c9a8-11e9-817e-f0ce7de734e5.png)

Not compatible with the new `rust-lang/stdarch`.

**Comment by workingjubilee** [comment]
Was resolved in #267
