### ISSUE TITLE
serde derives

### ISSUE THREAD

**Issue by vadixidav** [rust-lang/packed_simd#269]
Unless this crate needs to remain exactly as-is to be added to std, I believe that `serde` derives for `Serialize` and `Deserialize` should be added behind a feature gate. This would be quite helpful in my case where I have a data structure that abstracts over both `packed_simd` primitives and some normal numbers, but only implements those traits if the type it contains also implements them. I could create wrapper types around packed_simd, but I want to see if this would be accepted upstream first.

**Comment by Lokathor** [comment]
Hello. I'm a member of the new [Portable SIMD Project](https://github.com/rust-lang/project-portable-simd).

Going forward, the project group will be developing a [stdsimd](https://github.com/rust-lang/stdsimd) crate, which will be eventually be stabilized within the standard library under `core::simd` and `std::simd`. The design of `stdsimd` will likely be *similar* to the `packed_simd` crate in terms of practical usage, but there will inevitably be small changes in the transition.

Of course, this will take quite a bit of time to develop and stabilize. Accordingly, the project group will take over maintenance of the `packed_simd` crate, and we will at least ensure that it keeps building.

Broadly speaking, we are not planning to develop `packed_simd` any further. It should be considered to be in long-term maintenance mode, and when `stdsimd` is eventually stabilized then `packed_simd` will become completely deprecated.

At that time, `serde` will be able to add impls for the new SIMD types the same as it has impls for other `core` types like `f32` and `i64` and such. You won't even have to derive anything yourself.

---

We're trying to triage the issues a bit, so I'm going to close this. For more questions, you can post to the [Portable SIMD Project Group Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257879-project-portable-simd). If you've never used the zulip before it'll ask you to log in, but you can sign in with your GitHub account, so you don't need to do any new account setup stuff.
