### ISSUE TITLE
Move Repository To rust-lang

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/packed_simd#276]
Hello, the current `rust-lang-nursery` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead. 

### How Do I Move To `rust-lang`?
You won't be able to transfer your repository directly, you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation.

### Deprecating
If you no longer intend to maintain this repository, please let us know and we will take of deprecating the project.

**Comment by gnzlbg** [comment]
@pietroalbini how did you do this for `stdarch` ? The same should probably be done here.

**Comment by pietroalbini** [comment]
This is not as trivial as CI might break during the move...

**Comment by gnzlbg** [comment]
I was going to move this to github actions at some point to avoid taking CI time away from libc, so... I guess I'll have one more reason to do that after the move if that breaks CI, and I kind of see that as a feature 😆

**Comment by pietroalbini** [comment]
Ok, transferred the repository.

**Comment by gnzlbg** [comment]
Thank you!

**Comment by pietroalbini** [comment]
Also configured redirects for GitHub pages.
