### ISSUE TITLE
Can I transmute `&mut [f32]` to `&mut f32x8`?

### ISSUE THREAD

**Issue by phlopsi** [rust-lang/packed_simd#279]
I'm looking into abstracting the iteration over a 64-byte-aligned slice in f32x8 chunks and I need the item for both mutation and calculation.

This is my code, so far:
```
#[repr(align(64))]
struct AlignedF32Slice([f32]);

struct F32x8ChunksExactMut<'a>(ChunksExactMut<'a, f32>);

impl<'a> F32x8ChunksExactMut<'a> {
    pub fn into_remainder(self) -> &'a mut [f32] {
        self.0.into_remainder()
    }
}

impl<'a> Iterator for F32x8ChunksExactMut<'a> {
    type Item = &'a mut f32x8;

    #[inline]
    fn next(&mut self) -> Option<Self::Item> {
        unsafe {
            Option::Some(&mut *(self.0.next()?.as_mut_ptr() as *mut f32x8))
        }
    }
}
```
What I'm currently doing:
```
fn vectorized_lgc_assign_same(slice: &mut [f32]) {
    let mut scalars = slice.chunks_exact_mut(8);

    for scalar in &mut scalars {
        lgc_f32x8(f32x8::from_slice_unaligned(scalar)).write_to_slice_unaligned(scalar);
    }
```
What I hope to do:
```
fn vectorized_lgc_assign_same(slice: &mut AlignedF32Slice) {
    let mut chunks = slice.f32x8_chunks_exact_mut();

    for vector in &mut chunks {
        *vector = lgc_f32x8(*vector);
    }
```
In particular, I need to know if `&mut *(self.0.next()?.as_mut_ptr() as *mut f32x8)` is UB or not for my aligned slice. Also, if there's any better solution than what I'm doing, I'll gladly accept any tips.

**Comment by Lokathor** [comment]
Assuming that the slice is suitably aligned and of the correct length, you can transmute references like this, yes.

---

We're trying to triage this repo's issues a bit so I'll close this up, but you can post in the Zulip for the [Portable SIMD Project](https://rust-lang.zulipchat.com/#narrow/stream/257879-project-portable-simd) if you have more questions. It will ask you to make an account if you've never used Zulip before, but you can just log in with your github account so you don't have to do a big sign up for anything new.
