### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by nkconnor** [rust-lang/packed_simd#282]
#213 https://github.com/rust-lang/rfcs/pull/2366

@gnzlbg seems like the project isn't moving forward and major doubts about whether it will. The README is a little misleading, I think, creating the impression that the RFC is open:

>This aims to be a 100% conforming implementation of Rust RFC 2366 for stabilization.

Can you comment on the project status?

**Comment by Lokathor** [comment]
Hello. I'm a member of the new [Portable SIMD Project](https://github.com/rust-lang/project-portable-simd).

Going forward, the project group will be developing a [stdsimd](https://github.com/rust-lang/stdsimd) crate, which will be eventually be stabilized within the standard library under `core::simd` and `std::simd`. The design of `stdsimd` will likely be *similar* to the `packed_simd` crate in terms of practical usage, but there will inevitably be small changes in the transition.

Of course, this will take quite a bit of time to develop and stabilize. Accordingly, the project group will take over maintenance of the `packed_simd` crate, and we will at least ensure that it keeps building (such as fixing up the recent [mmx related issues](https://github.com/rust-lang/packed_simd/issues/288).

Broadly speaking, we are not planning to develop `packed_simd` any further. It should be considered to be in long-term maintenance mode, and when `stdsimd` is eventually stabilized then `packed_simd` will become completely deprecated.

---

We're trying to triage the issues a bit, so I'm going to close this. For more questions, you can post to the [Portable SIMD Project Group Zulip](https://rust-lang.zulipchat.com/#narrow/stream/257879-project-portable-simd). If you've never used the zulip before it'll ask you to log in, but you can sign in with your GitHub account, so you don't need to do any new account setup stuff.
