### ISSUE TITLE
packed_simd seems incompatible with libm 0.2

### ISSUE THREAD

**Issue by workingjubilee** [rust-lang/packed_simd#294]
Probably not going to see any movement on this, just thought it was interesting enough to note.

**Comment by eclipseo** [comment]
Could it be bumped to 1.0 please?

**Comment by Lokathor** [comment]
do you mean 0.2.1?

**Comment by eclipseo** [comment]
> do you mean 0.2.1?

Yes, I think it could be removed entirely. I'm proposing a PR, but I'm not sure if it is ok.
