### ISSUE TITLE
please update crates.io version to 0.3.4 :)

### ISSUE THREAD

**Issue by xMAC94x** [rust-lang/packed_simd#298]

**Comment by krojew** [comment]
0.3.3 doesn't build on current nightly, so 0.3.4 would be nice to have :)

**Comment by Lokathor** [comment]
Yeah, we're working on that, sorry!

The person that was previously the publisher of the crate is no longer available. We're trying to contact them or work on a work-around of some sort. If the crates.io folks can't help us out, we might post the 0.3.4 version under an alternative name as a last resort.

**Comment by workingjubilee** [comment]
We have went forward with publishing this as packed_simd_2! Apologies, it seems this is the best we can do for now.

**Comment by workingjubilee** [comment]
I suggest updating your Cargo.toml like so:

```toml
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
```
