### ISSUE TITLE
Reverse function of vector mask `.bitmask`

### ISSUE THREAD

**Issue by jhorstmann** [rust-lang/packed_simd#301]
I'm looking for the reverse equivalent to (m32x8, m64x8, ..).bitmask(), meaning I have an `u8` and want to create an 8-lane vector mask out of it. Ideally the same would also work for 16-lane types and `u16` and so on.

Maybe I'm just missing the obvious implementation, but if not this seems to be a very useful feature addition for generic simd code.

**Comment by TheIronBorn** [comment]
something like this could work
```rust
fn inverse_bitmask(x: u16) -> m8x16 {
    let splat = u8x16::from_bits(u16x8::splat(x));
    let isolated_bits = splat & _some_isolate_mask;
    let mask = isolated_bits.eq(_some_isolate_mask);
    shuffle!(mask, _some_shuffle_control) // must reorder
}
```

unsure how well this works on platforms without easy byte/etc shuffling

**Comment by Lokathor** [comment]
This crate is winding down, but if you file this request over in the new [stdsimd](https://github.com/rust-lang/stdsimd) repo then we'd be happy to try getting this in when time permits.

**Comment by jhorstmann** [comment]
Closing since the [`from_bitmask` function exists in portable_simd now](https://rust-lang.github.io/portable-simd/core_simd/struct.Mask.html#method.from_bitmask).
