### ISSUE TITLE
Please push current (0.3.4) upstream to https://crates.io/crates/packed_simd

### ISSUE THREAD

**Issue by MarkusZoppelt** [rust-lang/packed_simd#303]
The current release (0.3.3) is causing problems on Zen 2 AMD Ryzen CPUs

**Fix: Push current HEAD to crates.io**

e.g., see https://github.com/dalek-cryptography/curve25519-dalek/issues/333

**Comment by Lokathor** [comment]
We cannot. We lack the crates.io permissions. The original maintainer is out of contact.

If you adjust your dependency entry like this it should pick up the crate we published under an alternative name.
```toml
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
```

**Comment by MarkusZoppelt** [comment]
> The original maintainer is out of contact.

Well... this is not good.

We will use the workaround. Thanks for your answer!
