### ISSUE TITLE
No equivalent for `_mm_shuffle_ps`

### ISSUE THREAD

**Issue by Benjamin-L** [rust-lang/packed_simd#312]
I'm trying to implement a lookup table of shuffle values, and discovered that there's no way to call `_mm_shuffle_ps` with `packed_simd`. The `shuffle1_dyn` method only works by passing a SIMD vector of the same size, which is sub optimal for my case because it takes 4x more memory than is strictly necessary. Ideally there would be a way to shuffle a 4-wide vector with a dynamic `u8`.

**Comment by Lokathor** [comment]
Hello.

New development is no longer happening on this crate.

All new work is happening in a fresh crate over here: https://github.com/rust-lang/stdsimd
