### ISSUE TITLE
appveyor build bots run out of memory

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/packed_simd#39]
All ~~3 out of 4~~ appveyor build bots currently run out of memory.

We should try to find a way to minimize memory consumption in the `ci/run.sh` file. 

A good start would be to switch to:

* single job: `--jobs 1` / `CARGO_BUILD_JOBS=1`
* single code-gen unit: `RUSTFLAGS="-C codegen-units=1"`
* no debug info `RUSTFLAGS="-C debuginfo=0"`

**Comment by michaelwoerister** [comment]
`CARGO_INCREMENTAL=0` still works, yes.
